### ISSUE TITLE
please add bookmark to pdf

### ISSUE THREAD

**Issue by wangyq** [janishar/mit-deep-learning-book-pdf#4]
The book will be great if has bookmark.

**Comment by janishar** [comment]
@wangyq Yes you are right. I am not getting time to do it.

**Comment by TimAl** [comment]
[deeplearningbook.pdf](https://github.com/janishar/mit-deep-learning-book-pdf/files/1364429/deeplearningbook.pdf)
Voilà; the complete book and each chapter has a it's own bookmark

**Comment by mfoglio** [comment]
What is the difference between the 3 pdf?
- `complete-book-bookmarked-pdf/deeplearningbook.pdf` does not seem to have bookmarks (according to Preview on macOS) but it has working hyperlinks 
- `complete-book-pdf/deeplearningbook.pdf seems equal to ``complete-book-bookmarked-pdf/deeplearningbook.pdf`
- `complete-book-pdf/Ian Goodfellow, Yoshua Bengio, Aaron Courville - Deep Learning (2017, MIT)` seems equal to the other two but with no hyperlinks working. Interestingly, it's a little bigger in size.
All 3 pdf files have 800 pages, not sure if the content is exactly the same or if some include some corrections.
